name: Deploy ArchiveTGFilezBot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: TG_BOT_TOKEN
        env:
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN}}